name: Python CI

on:
  push:
    branches:
      - database  # Trigger the workflow on pushes to the database branch
  pull_request:
    branches:
      - database

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13' 

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install required dependencies

    # Run tests
    - name: Run tests
      run: |
        pytest  # Assuming you're using pytest for unit tests
